package com.gpfcomics.deepcompare.ui;

import lombok.Getter;

import javax.swing.*;
import java.awt.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class StartWindow {

    @Getter
    private JPanel rootPanel;
    private JButton btnStart;
    private JButton btnAbout;
    private JButton btnClose;
    private JButton btnOptions;
    private JButton btnTargetBrowse;
    private JTextField txtTarget;
    private JButton btnSourceBrowse;
    private JTextField txtSource;

    public StartWindow(JFrame parent) {

        btnSourceBrowse.addActionListener(e -> {
            browseForPath("Source", txtSource);
        });

        btnTargetBrowse.addActionListener(e -> {
            browseForPath("Target", txtTarget);
        });

        btnOptions.addActionListener(e -> {
            JOptionPane.showMessageDialog(
                    null,
                    "Not implemented yet!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        });

        btnStart.addActionListener(e -> {
            JOptionPane.showMessageDialog(
                    null,
                    "Not implemented yet!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        });

        btnAbout.addActionListener(e -> {
            AboutDialog dialog = new AboutDialog(parent);
            dialog.pack();
            dialog.setVisible(true);
        });

        btnClose.addActionListener(e -> {
            System.exit(0);
        });

    }

    private void browseForPath(String label, JTextField targetField) {
        try {
            String pathString = targetField.getText().trim();
            Path startPath = Paths.get(pathString);
            try {
                if (
                        pathString.isEmpty() ||
                        !Files.exists(startPath) ||
                        !Files.isDirectory(startPath)
                ) {
                    pathString = System.getProperty("user.home");
                }
            } catch (Exception ex) {
                targetField.setText("");
                pathString = System.getProperty("user.home");
            }
            JFileChooser chooser = new JFileChooser(pathString);
            chooser.setDialogTitle("Select " + label + " Folder");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                targetField.setText(chooser.getSelectedFile().getAbsolutePath());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Error trying to find the " + label.toLowerCase() + " path!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.add(panel1, BorderLayout.SOUTH);
        btnStart = new JButton();
        btnStart.setText("Start");
        panel1.add(btnStart);
        btnAbout = new JButton();
        btnAbout.setText("About...");
        panel1.add(btnAbout);
        btnClose = new JButton();
        btnClose.setText("Close");
        panel1.add(btnClose);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.SOUTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.add(panel4, BorderLayout.CENTER);
        btnOptions = new JButton();
        btnOptions.setText("Comparison Options...");
        panel4.add(btnOptions);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel2.add(panel5, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        panel5.add(panel6, BorderLayout.SOUTH);
        btnTargetBrowse = new JButton();
        btnTargetBrowse.setLabel("Browse...");
        btnTargetBrowse.setText("Browse...");
        panel6.add(btnTargetBrowse, BorderLayout.EAST);
        txtTarget = new JTextField();
        panel6.add(txtTarget, BorderLayout.CENTER);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        panel5.add(panel7, BorderLayout.CENTER);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new BorderLayout(0, 0));
        panel7.add(panel8, BorderLayout.SOUTH);
        final JLabel label1 = new JLabel();
        label1.setText("Target Folder:");
        panel8.add(label1, BorderLayout.WEST);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new BorderLayout(0, 0));
        panel7.add(panel9, BorderLayout.CENTER);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        panel9.add(panel10, BorderLayout.SOUTH);
        btnSourceBrowse = new JButton();
        btnSourceBrowse.setLabel("Browse...");
        btnSourceBrowse.setText("Browse...");
        panel10.add(btnSourceBrowse, BorderLayout.EAST);
        txtSource = new JTextField();
        panel10.add(txtSource, BorderLayout.CENTER);
        final JPanel panel11 = new JPanel();
        panel11.setLayout(new BorderLayout(0, 0));
        panel9.add(panel11, BorderLayout.CENTER);
        final JPanel panel12 = new JPanel();
        panel12.setLayout(new BorderLayout(0, 0));
        panel11.add(panel12, BorderLayout.SOUTH);
        final JLabel label2 = new JLabel();
        label2.setText("Source Folder:");
        panel11.add(label2, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
